# Generated by Django 5.2.6 on 2025-09-16 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='Número de Telefone')),
                ('public_place', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('city', models.CharField(max_length=100, verbose_name='Município')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('property_number', models.CharField(max_length=5, verbose_name='Número do Endereço')),
                ('complement_address', models.CharField(max_length=300, verbose_name='Complemento de Endereço')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa da Moto')),
                ('is_active', models.BooleanField(verbose_name='Está ativo')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='entregadores/', verbose_name='Foto do Entregador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
            },
        ),
    ]
