# Generated by Django 5.2.6 on 2025-09-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverymen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='complement_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Complemento de Endereço'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='property_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número do Endereço'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
