# Generated by Django 5.2.6 on 2025-09-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverymen', '0002_alter_deliveryman_cep_alter_deliveryman_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='is_active',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10),
        ),
    ]
