# Generated by Django 5.2.6 on 2025-09-16 18:01

import order.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverymen', '0004_alter_deliveryman_id_alter_deliveryman_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[order.validators.validate_cep], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='contact_phone',
            field=models.CharField(max_length=11, validators=[order.validators.validate_phone_number], verbose_name='Número de Telefone'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='cpf',
            field=models.CharField(max_length=11, validators=[order.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
