# Generated by Django 5.2.6 on 2025-09-16 20:19

import order.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverymen', '0006_alter_deliveryman_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='plate',
            field=models.CharField(max_length=8, validators=[order.validators.validate_plate], verbose_name='Placa da Moto'),
        ),
    ]
