# Generated by Django 5.2.6 on 2025-09-17 20:11

import order.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverymen', '0007_alter_deliveryman_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[order.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
