# Generated by Django 5.2.6 on 2025-09-16 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('public_place', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('city', models.CharField(max_length=100, verbose_name='Município')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('property_number', models.CharField(max_length=5, verbose_name='Número')),
                ('complement_address', models.CharField(max_length=300, verbose_name='Complemento de Endereço')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Número de Telefone')),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_contact', models.CharField(max_length=11, verbose_name='Contato do Whatsapp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
