# Generated by Django 5.2.6 on 2025-09-16 18:01

import order.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_id_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cep',
            field=models.CharField(max_length=8, validators=[order.validators.validate_cep], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[order.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[order.validators.validate_phone_number], verbose_name='Número de Telefone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp_contact',
            field=models.CharField(max_length=11, validators=[order.validators.validate_phone_number], verbose_name='Contato do Whatsapp'),
        ),
    ]
