# Generated by Django 5.2.6 on 2025-09-16 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverymen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='Telefone de Contato')),
                ('public_place', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('city', models.CharField(max_length=100, verbose_name='Município')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('property_number', models.CharField(max_length=5, verbose_name='Número do Endereço')),
                ('complement_address', models.CharField(max_length=300, verbose_name='Complemento de Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Total')),
                ('order_code', models.PositiveIntegerField(verbose_name='Código de Pedido')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('payment_status', models.BooleanField(verbose_name='Status de Pagamento')),
                ('note', models.TextField(max_length=500, verbose_name='Observações')),
                ('delivery_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveryorder_deliveryman', to='deliverymen.deliveryman', verbose_name='Entregador')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveryorder_client', to='order.client', verbose_name='Destinatário')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de Entrega',
                'verbose_name_plural': 'Ordens de Entregas',
                'ordering': ['order_code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, verbose_name='Nome de Produto')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Quantidade de Produto')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Produto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['product_name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_product', to='order.product', verbose_name='Produto do Cliente'),
        ),
    ]
